export const LOAD_COINS_SUCCESS = "LOAD_COINS_SUCCESS";
export const LOAD_QUOTES_SUCCESS = "LOAD_QUOTES_SUCCESS";
export const ADD_TO_PORTFOLIO = "ADD_TO_PORTFOLIO";
export const REMOVE_FROM_PORTFOLIO = "REMOVE_FROM_PORTFOLIO";
